### ISSUE TITLE
Odd jumping behavior

### ISSUE THREAD

**Issue by qixils** [TurtleP/Turtle-Tale#12]
Normal jumps act as shell jumps(?) in certain situations.

- Shell dash into a wall and keep holding the direction towards the wall

- Hold the jump button (while still holding the direction)

Expected result: Turtle jumps at least 2 blocks high

Actual result: Turtle jumps less than a block

**Comment by TurtleP** [comment]
Does this still happen?

**Comment by qixils** [comment]
Yes. It seems the turtle actually is jumping one block high, but it's not detecting that right is being held.

**Comment by TurtleP** [comment]
Yep. That makes sense. I'll work on it when I get home.
