### ISSUE TITLE
First dragon cutscene unskippable

### ISSUE THREAD

**Issue by qixils** [TurtleP/Turtle-Tale#17]
also known as "the one cutscene that comes after the sleeping one"

**Comment by TurtleP** [comment]
I'll look at this soon. Not sure why it won't work here, but I have an idea of what's wrong.

**Comment by TurtleP** [comment]
I've not looked into it yet, but do you have any other details, Noah?

**Comment by hatninja** [comment]
Seems like to me it soft-locks if you try to skip it.

**Comment by TurtleP** [comment]
I think it's to do with how I listed function to omit for skipping. It was bugged. I'll redo it.
