### ISSUE TITLE
Many lovely bugs

### ISSUE THREAD

**Issue by LiquidFenrir** [TurtleP/Turtle-Tale#20]
Not really ordered, I'll add more as I find them

* **Softlock:** save while dying (when the screen starts getting dark) and you'll be locked

* _~~**Lock-in movement:** get in shell mode (dpad-down), start moving in a direction (left/right), then jump (B), and release the direction and down buttons _BEFORE TOUCHING THE GROUND_, and you will keep moving in this direction, in shell mode.
It will register **1** more left or right press, so you can change direction if needed.
If you change screens like this, the movement will carry over but the shell mode won't.
To get back to normal, just press the shell mode button again.~~_

* **Lock-in movement V2:** Start shoulder bashing near a screen edge, and release while the screen turns dark. When the next area loads, you'll be stuck in movement.
If you're locked going to the left, you can go to the right with the directional buttons, but if you're locked going to the right, you can't change directions.
To get back to normal, just press the Y button  and **same** directional button as the direction you're locked in, then release.
OR, change screens while pressing/holding the a directional button (but not the Y button).

* **Unable to go back:** when reaching the second right screen after the home screen (the one that leads to the caves under), you can't go back to the screens to the left.
With the latest commit (6f6963ebd6bc9fa84e30df481c6df3eec871b254 at the time), you're completely locked in this screen as you can't go forward either.

* **Wrong screen change:** after exiting the cave, if you go left, instead of returning to the cave, it sends you back to the first screen right of the home one

* **No damage:** if you are in shell mode when you die, you won't lose hearts but you will get teleported back normally

* **Invincibility after death:** when you fall in a hole, you lose a heart and get teleported back, along with going invincible for a few seconds If you fall again while invincible, you get teleported back, but don't lose a heart. **The invincibility timer also doesn't reset**, so you can actually die, if combined with the **movement lock-in** (which also lasts through teleportation), because you repeatedly fall in the hole.

* **Control during the intro:** you can get up during the intro, but can't move. It will put you back into the bed at the "ow" though

* _~~**Background color during the intro:** (more opinion than bug), the background color (blue) contrasts too much with the wall color, it should be some kind of red or purple.
Alternatively, you could make the room texture larger so it doesnt expose the background color at all while it shakes.
In my opinion, the shaking should also be reduced, to be closer to Pokémon mystery dungeon red/blue~~_

* **Screen splitting:** If you fall in the first hole (first screen right of the home screen), you get teleported back and the screen shakes, but the shaking leaves a vertical line through the sky/background.
[Image attached](http://i.imgur.com/15YMSkt.png)

* **Text wrapping:** a few words are displayed "out of bounds". "knowledge", "countless", "it"...

* **Shoulder bash recoil cancel:** in the cave, after opening the chest, you're able to shoulder bash using Y. when hitting one of the blue crates, it gets damaged and you get some recoil/bounce back. you can cancel the bounce by just letting go of the Y key

* data abort when saving: random? Also happens when opening the game? deleting the save fixes it

* The fps randomly goes lower. can't really explain it

Missing features:

* _~~unable to delete a save: Yeah, you can just edit/delete the save file, but that would be nice to have :P~~_

* _~~circle pad control? rather than only the dpad~~_

* sprinting? the turtle is goddamn slow, but maybe more to do with how the fps is 30 most of the time

* put the turtle further back when dying from a fall. currently on the last pixel, pretty spooky seeing a levitating turtle

**Comment by TurtleP** [comment]
`unable to delete a save: Yeah, you can just edit/delete the save file, but that would be nice to have :P`
- Press 'R' and it highlights save data, press 'A' to delete it 

`circle pad control? rather than only the dpad`
- Press 'Select' and it toggles Circle Pad

The other things I'll take into consideration and I'll get to fix those bugs when I can.

**Comment by LiquidFenrir** [comment]
Thanks, didn't know.
Edited to show as "fixed" (strikethrough and italics)

**Comment by LiquidFenrir** [comment]
Found how to reliably lock the movement, edited the post.

**Comment by TurtleP** [comment]
Soon:tm: I'll commit some changes to include fixes for the following:

`Unable to go back`
`Wrong screen change`
`Control during the intro`
`Text wrapping`
`data abort when saving`

**Comment by Ryuzaki-MrL** [comment]
Opening a textbox while holding left or right causes the turtle to keep moving on that direction after the text is gone.

**Comment by TurtleP** [comment]
Currently with the `next` branch these issues are fixed from what I can tell. I'll close this now. 👍
