### ISSUE TITLE
Phoenix cutscene doesn't play, breaks the game.

### ISSUE THREAD

**Issue by hatninja** [TurtleP/Turtle-Tale#22]
I quit after the first cutscene, thanks to the immobilizing glitch. When i exit the door, no cutscene plays and another music track plays on top of the old one. Attempting to go back or continue results in crashes.

**Comment by TurtleP** [comment]
I'll fix this soon. Not sure if I have time, but if I fix it I'll close this.

**Comment by TurtleP** [comment]
Fixed for a future commit ✔️
