### ISSUE TITLE
Random Softlocks (Pressing Start/Area Change, etc)

### ISSUE THREAD

**Issue by yerWizard** [TurtleP/Turtle-Tale#24]
Pressing start while playing freezes the game except the music also the home button stops working. Im using the CIA version on a N3DS.

**Comment by TurtleP** [comment]
Yeah, it happens to softlock at some other points too. Not sure what's causing it, but I think it has to do with Love Potion.. and gdb says it's a corrupt stack. Citra runs it fine, which makes no sense.

**Comment by rweichler** [comment]
Might be a segfault.

**Comment by TurtleP** [comment]
@rweichler I'm trying to track down the source of it, but no luck so far. It's really annoying :|

**Comment by rweichler** [comment]
Yeah it's super annoying how citra/3DS doesn't crash on segfaults. It happilly just corrupts memory, and then later down the line it'll crash. I ran into a similar issue for my 3DS homebrew. Ended up having to port it to desktop to find it >_>

**Comment by TurtleP** [comment]
I'll see if there's *some* way to set a flag to do something like that..

**Comment by TurtleP** [comment]
@rweichler I've updated the [Love Potion](https://github.com/TurtleP/LovePotion) repo with the code Turtle Tale uses (it's more recent). I've also pushed the fix for the inventory crash, so maybe you or others can help look into it a bit more than I can.

**Comment by TurtleP** [comment]
The last gdb run I did produced this:

```
(gdb) backtrace
#0  svcArbitrateAddress () at /home/jpost/ctrulib/libctru/source/svc.s:250
#1  0x0016dcf4 in gspWaitForAnyEvent ()
    at /home/jpost/ctrulib/libctru/source/services/gspgpu.c:106
#2  0x0016bc00 in gxCmdQueueWait (queue=<optimized out>,
    timeout=<optimized out>)
    at /home/jpost/ctrulib/libctru/source/gpu/gxqueue.c:117
#3  0x001651d0 in C3Di_WaitAndClearQueue (timeout=<optimized out>)
    at /home/jpost/citro3d/source/renderqueue.c:131
#4  0x00165464 in C3D_FrameBegin (flags=<optimized out>)
    at /home/jpost/citro3d/source/renderqueue.c:216
#5  0x00107c1c in love::Graphics::StartTarget (this=0x801aa00,
    target=0x801aa18)
    at /mnt/c/Users/jerem/Dropbox/Homebrew/3DS/TurtleTale/source/modules/graphics/graphics.cpp:549
#6  0x00107b90 in love::Graphics::Render (this=0x801aa00, screen=GFX_TOP,
    side=GFX_LEFT)
    at /mnt/c/Users/jerem/Dropbox/Homebrew/3DS/TurtleTale/source/modules/graphics/graphics.cpp:531
#7  0x0010178c in main (argc=0, argv=0x0)
    at /mnt/c/Users/jerem/Dropbox/Homebrew/3DS/TurtleTale/source/main.cpp:100
```

So my suspicion (and I just tested) is the GPU is softlocking. There's no need for it to do that either. I'll contact fincs and see if they can help.

Relevant code [here](https://github.com/TurtleP/LovePotion/blob/master/source/modules/graphics/graphics.cpp#L523)
