### ISSUE TITLE
Random freezing when loading another area (old 3DS)

### ISSUE THREAD

**Issue by Ryuzaki-MrL** [TurtleP/Turtle-Tale#25]
Sometimes the game freezes when you enter a new area/screen. It happens before the fadeout transition and neither the HOME or power button works afterwards.
I'm playing the CIA version on a bs9'd old 3ds running the latest luma3ds nightly.

**Comment by TurtleP** [comment]
See #24 (I'll just use that as the main thread for this)

**Comment by Ryuzaki-MrL** [comment]
Sorry for the duplicate issue. I see you've changed #24's title.

**Comment by TurtleP** [comment]
It's okay :)
