### ISSUE TITLE
Creating a save in slots 2 or 3 without one in slot 1 causes saves not to persist

### ISSUE THREAD

**Issue by 916253** [TurtleP/Turtle-Tale#3]
# Issue:
Starting the game with slot 2 or slot 3 when there is no save in slot 1 results in all saves being removed after the game is relaunched

## Steps to reproduce:
1) Start the game, being sure to choose slot 2 or slot 3, and making sure there is no save in slot 1
2) Save and quit
3) Close and Re-open the game

### Expected Result:
Game should have saved the save in slot 2 or 3

### Actual result:
Game did not allow any saves to persist, instead marking all save slots as blank

**Comment by TurtleP** [comment]
Fixed with commit cd7bcb4
