### ISSUE TITLE
Having multiple save files results in a Lua error (Malformed number)

### ISSUE THREAD

**Issue by 916253** [TurtleP/Turtle-Tale#4]
# Issue:
Creating a save in slot 2 or 3 after having a save in slot 1 results in a lua error occurring the next time the game is launched.

## Steps to reproduce:
1) Start the game, being sure to choose slot 2 or slot 3, and making sure there is already a save in slot 1
2) Save and quit
3) Close and Re-open the game

### Expected Result:
Game should have saved the save in slot 2 or 3 and proceeded as normal

### Actual result:
Game does not load, instead a Lua error screen is displayed

#### Error:

> sdmc:/LovePotion/TurtleTale/save.lua:3: malformed number near '12.29.2016'

**Comment by TurtleP** [comment]
Fixed with commit cd7bcb4
