### ISSUE TITLE
Objects don't vibrate on n3DS

### ISSUE THREAD

**Issue by qixils** [TurtleP/Turtle-Tale#7]
On PC during the intro, you can see certain house objects vibrating (ex. the bed) - this, however, doesn't happen on n3DS (and possibly o3DS, gave mine away and can't test)

**Comment by TurtleP** [comment]
I'll check my build I've got on my n3DS. Should be alright. I was trying to fix something on PC, and this is a minor case where the builds don't align properly in terms of operation.

**Comment by TurtleP** [comment]
Yeah, I updated the QR a day ago or so. Works fine now.
