### ISSUE TITLE
Enter key can't be used to load save [PC]

### ISSUE THREAD

**Issue by qixils** [TurtleP/Turtle-Tale#8]
Title is self-explanatory. Also applies to the Continue/Quit buttons on the Game Over screen.

**Comment by TurtleP** [comment]
The game isn't really meant to be for PC (broadly being Windows/macOS/Linux) but it is supposed to be *debuggable* on those platforms. That said, it's not too much of a big deal.

**Comment by TurtleP** [comment]
I'll reconsider the matter if I do allow it to be non-3DS exclusive. But I don't think that'll change any time soon.
